version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:80"
    volumes:
      - ./api:/    
    networks:
      - mynet

  vueapi:
    build:
      context: ./vue
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/app
    command: bash -c "npm install && npm run serve"
    networks:
      - mynet


networks:
  mynet:
